variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.6.1-jdk-8-slim

cache:
  paths:
    - .m2/repository

stages:
  - validate
  - build


# For merge requests do not `deploy` but only run `verify`.
# See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
.validate: &validate
  stage: validate
  script:
    - 'mvn $MAVEN_CLI_OPTS test-compile'

.verify: &verify
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

"Validate Maven structure":
  <<: *validate

"Build snapshot":
  <<: *verify

